name: coin_sage
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  flutter_lints: ^3.0.1
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.3.10
  flutter_riverpod: ^2.4.9
  awesome_notifications: ^0.9.2
  
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#03041C"
  image: assets/image/rupee.png
  color_dark: "#03041C"
  image_dark: assets/image/rupee.png
  
  android_12:
    image: assets/image/rupee.png
    icon_background_color: "#03041C"
    image_dark: assets/image/rupee.png
    icon_background_color_dark: "#03041C"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - 'assets/image/rupee.png'
    - 'assets/image/img1.png'
    - 'assets/image/splash_image1.png'
    - 'assets/image/splash_image2.png'
    - 'assets/image/coin_sage.jpg'
    - .env
  